# Setup
title:               Five Fifty-Four
tagline:             'exploring Sacred Harp data'
description:         ''
url:                 http://blog.fivefiftyfour.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Godfrey
  url:               https://spacetemple.com/mark
  email:             mark@spactemple.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
